admin_usuario:
    path:     /
    defaults: { _controller: "CursoBundle:AdminUsuario:index" }

admin_usuario_show:
    path:     /{id}/show
    defaults: { _controller: "CursoBundle:AdminUsuario:show" }

admin_usuario_new:
    path:     /new
    defaults: { _controller: "CursoBundle:AdminUsuario:new" }

admin_usuario_create:
    path:     /create
    defaults: { _controller: "CursoBundle:AdminUsuario:create" }
    methods:  POST

admin_usuario_edit:
    path:     /{id}/edit
    defaults: { _controller: "CursoBundle:AdminUsuario:edit" }

admin_usuario_update:
    path:     /{id}/update
    defaults: { _controller: "CursoBundle:AdminUsuario:update" }
    methods:  [POST, PUT]

admin_usuario_delete:
    path:     /{id}/delete
    defaults: { _controller: "CursoBundle:AdminUsuario:delete" }
    methods:  [POST, DELETE]
