security:
    encoders:
            Curso\CursoBundle\Entity\Usuario: md5
            Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER
            ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
            chain_provider:
                chain:
                    providers: [user_db, in_memory]
            user_db:
                entity:
                    class: Curso\CursoBundle\Entity\Usuario
                    property: email
            in_memory:
                memory:
                    users:
                        admin: { password: qwerty, roles:'ROLE_ADMIN'}

    firewalls:
            admin_area:
                pattern:    ^/admin
                http_basic: ~
#                form_login:
#                    login_path: /admin/login
#                    check_path: /admin/check
                logout:
                    path: /admin/logout
                    target: /
            secured_area:
                pattern:    ^/
                anonymous: ~
                form_login:
                    login_path: /login
                    check_path: /check
                logout:
                    path: /logout
                    target: /

    access_control:
            - { path: ^/admin, roles: ROLE_ADMIN }
            - { path: ^/usuario/perfil, roles: ROLE_USER }


## To get started with security, check out the documentation:
## http://symfony.com/doc/current/book/security.html
#security:
#
#    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
#    providers:
#        in_memory:
#            memory: ~
#
#    firewalls:
#        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        main:
#            anonymous: ~
#            # activate different ways to authenticate
#
#            # http_basic: ~
#            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate
#
#            # form_login: ~
#            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
